### 8-4-1. 예외 처리 코드

`try-catch-finally 블록` 은 생성자 내부와 메소드 내부에 작성되어 exception과 runtime exception이 발생할 경우 exception handling을 할 수 있도록 해줌.

try-catch-finally 블록은 다음과 같이 작성함.

```java
try {
	//예외 발생 가능 코드
} catch(예외클래스 e) {
	//예외 처리
} finally {
	//항상 실행
}
```

- try 블록의 코드가 예외 발생 없이 정상 실행되면 finally 블록의 코드를 실행함.
- try 블록의 코드에서 예외가 발생하면 catch 블록으로 이동하여 예외 처리 코드를 실행하고 finally 블록의 코드를 실행함.
- finally 블록은 생략 가능함.
- try 블록과 catch 블록에서 return 문을 사용하더라도 fianally 블록은 항상 실행됨.

👉🏻 [예제](https://github.com/gimhanul/Java/tree/master/src/exception/exception_handing)